apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Khairy01/DevOps.git
    path: argocd-app
    targetRevision: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: django-app
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
