apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Khairy01/DevOps.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: django-app
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
