version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "7000:7000"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: BibDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bonjoure
