version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: Bib
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mars
