name: CI/CD Pipeline

on:
  push:
    branches:
      - dev2
  pull_request:
    branches:
      - dev2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install -r requirements.txt


#      - name: Run tests
#        run: |
#          python manage.py test
#


#      - name: Lint and format code
#        run: |
          # Add commands for linting and formatting here
#        working-directory: ./path/to/your/django/app

      - name: Build Docker image
       run: |
          docker build -t devops_web:latest .


      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: 'fatou1801' #${{ secrets.DOCKER_USERNAME }}
          password: 'Harvarde18' #${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push your-django-app-image:latest





