apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: Qmli #base64 encoded
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: c2FsbDIwMTE=
  POSTGRES_PORT: NTQzMg==
