apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: app-django-container
          image: fatou01/app-django:latest #nom_image(push sur dockerhub)
          ports:
          - containerPort: 8000  #port du container
          env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres-url


