name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Start Docker containers
        run: |
          docker-compose up -d

      - name: Lint and format code
        run: |
          black . --check
          ruff check .
          
      - name: Run tests
        run: |
          docker-compose run -e DJANGO_SETTINGS_MODULE=final_devops.settings web pytest

            
      - name: Build Docker image
        run: |
          docker build -t mars2001/devops_web:latest .


      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push mars2001/devops_web:latest